import { Project, RequirementForm } from "../../types"

/** Nhãn loại phiếu — dùng trong tab Yêu cầu (không dùng tiêu đề CAPS như form web) */
export const FORM_TYPE_LABELS: Record<string, string> = {
  ecommerce: "Website bán hàng",
  landing_page: "Landing page",
  company_profile: "Website giới thiệu",
}

const DEMO_FORMS: Record<string, RequirementForm[]> = {
  PRJ001: [
    {
      id: "RF-PRJ001-1",
      leadId: "1",
      code: "YC-2026-001",
      title: "Phiếu yêu cầu — Website bán hàng",
      projectType: "ecommerce",
      isLocked: true,
      createdAt: "2026-06-15T10:30:00.000Z",
      lockedAt: "2026-06-20T14:00:00.000Z",
      publicLink: "/form/1",
      customer_name: "Nguyễn Văn A",
      customer_phone: "0901234567",
      customer_email: "nguyenvana@abcshop.vn",
      company: "Công ty TNHH ABC Shop",
      industry: "Thời trang & Phụ kiện",
      source: "Giới thiệu từ khách cũ",
      goal: "Bán hàng online, giảm phụ thuộc sàn TMĐT, tăng lợi nhuận biên",
      cta: "Mua ngay / Thêm giỏ hàng",
      kpi: "500 đơn/tháng sau 3 tháng go-live",
      main_product: "Quần áo nam nữ, phụ kiện thời trang",
      usp: "Hàng chính hãng, đổi trả 7 ngày, giao nhanh 2h nội thành",
      offers: "Freeship đơn từ 299k, giảm 10% đơn đầu",
      pricing: "Giá niêm yết + combo theo mùa",
      product_count: "Khoảng 200–300 SKU ban đầu",
      target_audience: "Nam nữ 22–40 tuổi, thu nhập trung bình–khá, TP.HCM & Hà Nội",
      insight: "Khách quen mua trên sàn nhưng muốn ưu đãi riêng và tích điểm",
      location: "TP.HCM (có giao toàn quốc)",
      user_flow: "Trang chủ → Danh mục → Chi tiết SP → Giỏ hàng → Thanh toán → Theo dõi đơn",
      structure: "Trang chủ, Danh mục, Sản phẩm, Giỏ hàng, Thanh toán, Tài khoản, Chính sách",
      sections: "Banner KM, Sản phẩm nổi bật, Flash sale, Review khách, Blog tips mặc đẹp",
      top_features: "Lọc size/màu, Tìm kiếm, Mã giảm giá, Đánh giá sản phẩm",
      payment_methods: "COD, Chuyển khoản, VNPay, Momo",
      order_handler: "NV bán hàng + kế toán xác nhận",
      order_process: "Đơn mới → Xác nhận → Đóng gói → Giao GHN/GHTK → Hoàn tất",
      brand_color: "#C62828 (đỏ chủ đạo), phụ trắng/xám",
      style: "Hiện đại, sạch, nhiều ảnh sản phẩm",
      references: "https://yame.vn\nhttps://canifa.com",
      hosting_status: "already",
      deadline: "30/09/2026",
      budget: "50–70 triệu",
      priority: "Thanh toán online + quản lý đơn mượt là ưu tiên số 1",
      notes: "Cần đồng bộ tồn kho với Excel trước, sau này nối API kho",
      payment_integrations: "VNPay, Momo",
      shipping_integrations: "GHN, GHTK",
      has_cart: true,
      has_online_payment: true,
      has_quick_order: true,
      has_user_account: true,
      has_wishlist: true,
      has_coupon: true,
      has_order_tracking: true,
      has_order_status: true,
      has_order_email: true,
      has_shipping_integration: true,
      has_admin: true,
      has_product_admin: true,
      has_order_admin: true,
      has_customer_admin: true,
      has_facebook_pixel: true,
      has_google_analytics: true,
      has_zalo_messenger: true,
      has_responsive: true,
      has_speed_optimized: true,
      has_seo: true,
      has_content: true,
      has_images: true,
      has_logo: true,
      attachments: [
        { id: "att-1", name: "Logo ABC Shop.png", url: "#", type: "file", uploadedAt: "2026-06-18T08:00:00.000Z", size: "240 KB" },
        { id: "att-2", name: "Catalog mùa Hè.pdf", url: "#", type: "file", uploadedAt: "2026-06-19T09:00:00.000Z", size: "4.2 MB" },
      ],
    },
    {
      id: "RF-PRJ001-2",
      leadId: "1",
      code: "YC-2026-002",
      title: "Phiếu bổ sung — Chiến dịch Landing Page Tết",
      projectType: "landing_page",
      isLocked: true,
      createdAt: "2026-06-25T09:00:00.000Z",
      lockedAt: "2026-06-28T16:30:00.000Z",
      customer_name: "Nguyễn Văn A",
      customer_phone: "0901234567",
      customer_email: "nguyenvana@abcshop.vn",
      company: "Công ty TNHH ABC Shop",
      goal: "Thu lead & bán voucher Tết qua landing riêng",
      cta: "Nhận voucher / Đăng ký nhận ưu đãi",
      kpi: "2.000 lead trong 2 tuần chạy ads",
      main_product: "Voucher giảm giá combo Tết",
      target_audience: "Khách hàng cũ + lookalike Facebook 25–45 tuổi",
      user_flow: "Ads → Landing → Form đăng ký → SMS voucher",
      structure: "Hero, Ưu đãi, Form đăng ký, FAQ, Footer",
      has_register_form: true,
      has_call_button: true,
      has_chat: true,
      has_facebook_pixel: true,
      has_google_analytics: true,
      has_responsive: true,
      has_speed_optimized: true,
      deadline: "15/12/2026",
      budget: "15–20 triệu (landing + tích hợp CRM đơn giản)",
      notes: "Landing tách domain riêng, redirect về shop chính sau khi nhận voucher",
    },
    {
      id: "RF-PRJ001-3",
      leadId: "2",
      code: "YC-2026-003",
      title: "Phiếu yêu cầu — Website giới thiệu (bản nháp)",
      projectType: "company_profile",
      isLocked: false,
      createdAt: "2026-07-01T11:00:00.000Z",
      customer_name: "Lê Thị B",
      customer_phone: "0912345678",
      customer_email: "lethib@example.com",
      company: "Công ty CP Dịch vụ XYZ",
      services: "Tư vấn thuế, Kế toán doanh nghiệp, Báo cáo tài chính",
      strengths: "15 năm kinh nghiệm, đội ngũ CPA, hỗ trợ SME",
      has_contact_form: true,
      has_google_maps: true,
      has_news: true,
      has_responsive: true,
      has_seo: true,
      deadline: "31/10/2026",
      notes: "Khách đang soạn nội dung, chưa gửi bản cuối",
    },
  ],
}

export function getDemoRequirementForms(projectId: string): RequirementForm[] {
  return DEMO_FORMS[projectId] ?? []
}

export function mergeProjectRequirementDemo(project: Project): Project {
  const forms = getDemoRequirementForms(project.id)
  if (forms.length === 0) return project
  return {
    ...project,
    requirementForms: forms,
    leadId: project.leadId ?? forms[0]?.leadId,
  }
}
